Controllers/ProductRelatedController.cs
using E_Commerce.Areas.Admin.Models;
using E_Commerce.Areas.Admin.Repository;
using E_Commerce.Models;
using E_Commerce.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace E_Commerce.Controllers
{

    [Authorize(Roles = "Admin,User")]

    public class ProductRelatedController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICartOrderRepository _cartOrderRepository;

        public ProductRelatedController(IProductRepository productRepository, ICartOrderRepository cartOrderRepository)
        {
            this._productRepository = productRepository;
            this._cartOrderRepository = cartOrderRepository;
        }
        [AllowAnonymous]
        public IActionResult GetProduct(int id)
        {

            var product = _productRepository.GetProductModel(id);
            return View(product);
        }

        [AllowAnonymous]
        public IActionResult GetProductDetails(int id)
        {
            var product = _productRepository.GetProductModel(id);
            return View(product);
        }

        public async Task<IActionResult> AddToCart(ProductModel product, string productStatus)
        {

            var insertedCartId = await _cartOrderRepository.AddToCart(product, productStatus);
            if (insertedCartId>0)
            {
                TempData["IsAddedIntoCart"] = "True";
                TempData["CartCount"] = _cartOrderRepository.getCartCount().ToString();
                if (productStatus == "order")
                {
                    return RedirectToAction("PlaceOrder",new { orderId =insertedCartId});
                }
            }
            else
            {
                TempData["IsAddedIntoCart"] = "False";
            }
            return RedirectToAction("GetProduct",new { id=product.Id});
        }
        public IActionResult AllCartProducts()
        {
            var carts=_productRepository.AllCartProducts("cart",0);
            return View(carts);
        }

        public async Task<IActionResult> RemoveFromCart(int cartId, string status)
        {
            var isRemoved = await _cartOrderRepository.RemoveCartProduct(cartId);
            TempData["CartCount"] = _cartOrderRepository.getCartCount().ToString();
            TempData["IsRemoved"] = "True";


            // for checking that it's removed from cart or order page
            return RedirectToAction(status == null ? "AllCartProducts": "pandingorders");
            
        }


        //this view only for select options like address,payment method, etc
        public IActionResult PlaceOrder(int? orderId)
        {  

            if(orderId == null)
            {
                // when we do want to checkout from cart page
                var order =_cartOrderRepository.GetPlaceOrderModel(0);
               
                return View(order);

            }
            else
            {
                var order = _cartOrderRepository.GetPlaceOrderModel((int)orderId);
                return View(order);
            }          
        }


        //this is for placing order 
        [HttpPost]

        public IActionResult PlaceOrder(PlaceOrderModel placeOrderModel)
        {
            var order = _cartOrderRepository.GetPlaceOrderModel(placeOrderModel.CartProductId);
            if (_cartOrderRepository.CompleteOrder(placeOrderModel))
            {
                TempData["IsOrder"] = "True";

            }
            return View(order);
        }

        
        // this is for getting all ordered products by this user
        public  IActionResult AllOrders()
        {
            var orders=_cartOrderRepository.GetAllOrders();
            return View(orders);
        }


        public IActionResult PlaceSingleOrder(ProductModel product)
        {

            return View();
        }


        public IActionResult PandingOrders()
        {
            var pandingOrders= _productRepository.AllCartProducts("order",0);
            return View(pandingOrders);
        }

        public async Task<IActionResult> CancelOrder(int id)
        {
            if (await _cartOrderRepository.CancelOrder(id))
            {
                TempData["IsOrderCancel"] = "True"; 
            }
            else
            {
                TempData["IsOrderCancel"] = "False"; 

            }
            return RedirectToAction("AllOrders");
        }
    }
}

Views/ProductRelated/AllCartProducts.cshtml
@model List<CartModel>

@{ 
    var GrandTotal = 0;
    var GrandDiscount = 0;
}
<style>
    .cartListImageDiv{
        max-height:11rem;
        max-width:6rem;
    }
    .productName, .productSaler {
        line-height: 18px;
    }
    .productSaler{
        font-size:1rem;
        color:dimgray;
    }

    .productQuantity{
        line-height:18px;
    }

    .wdtotal{
        color:darkgray;
    }

    .cartDiscount{
        font-size:15px;
        opacity:0.8;
    }
    .placeOrderButton{
        background-color:darkorange;
        border-color:darkorange;
        border-radius:unset;
        margin-bottom:1rem;
       
    }
    .sidebarTextSize{
        font-size:10px;
    }
</style>

    @if (TempData["IsRemoved"] != null) {
        if (TempData["IsRemoved"].ToString()=="True") {
            <script>
                swal("Removed.!", "Product removed from cart successfully", "success");
            </script>
        }
        else
        {
            <script>
                swal("Error.!", "Product does not removed from cart..!", "info");
            </script>
        }
    }



@if(Model.Count == 0)
{
    <div class="card container">
        <div class="card-body">
        <h3>My cart</h3>

            <div class="row">
                <div class="col-4 offset-4 ">

                    <img src="/svgs/Empty-amico.svg"  alt="Alternate Text" />
                </div>
                <div class="text-center">
                    <h3>Your cart is empty..!</h3>
                    <p>Start exploring item..!</p>
                </div>
            </div>
        </div>
    </div>
    
}else
{ 
    <div class="container">
        <div class="row flex-row ">
            <div class="col-md-8 order-2 order-lg-1 ">
                <div class="card">
                    <div class="card-header bg-white flex-row">
                        <h4 class="d-inline-block">Cart items(@Model.Count)</h4>
                        <a  asp-controller="Home" asp-action="Index" class="text-secondary fw-bold float-end text-decoration-none pl-2"> Go To Home</a>
                    </div>
                    <div class="card-body">

                        @foreach (var item in Model)
                        {
                            // TODO: Working on opacity while insufficient stock
                            <div class="mb-2 row border p-2 @(item.Quantity > item.ProductStock ? "opacity-50 ":"not match" )" data-bs-toggle="tooltip" data-bs-placement="left" title="">
                                <div class="col-3 col-sm-3 col-md-3 col-lg-2">

                                    <div class="cartListImageDiv border p-2">
                                        <img class="img-fluid cartImage" src="@item.ProductCoverImageUrl" alt="Alternate Text" />
                                    </div>
                                </div>

                                @*7 in*@
                                <div class="col-7">
                                    <p class="fs-5 productName">
                                        @item.ProductName
                                    </p>

                                    <p class="opacity-100 text-danger">
                                        @(item.Quantity > item.ProductStock ?"This product is out of stock stock..! so remove it or proceed without it.! " :"")
                                    </p>
                                    <p class="productSaler">Saler name: @item.ProductSaler  

                                    @{


                                        @if (item.ProductStock > item.Quantity)
                                        {

                                            GrandTotal +=(int)item.TotalPrice;
                                            GrandDiscount += (int)item.TotalDiscount;
                                        }

                                        <div>
                                            @*<p>Discount :: @item.TotalDiscount   TOTAL :: @item.TotalPrice</p>*@
                                            <span class="fw-bold  me-1">₹@item.DiscountedPrice</span> <span class="wdtotal"><strike> ₹@item.TotalPrice</strike></span> <span class="cartDiscount fw-bold text-success">@item.ProductDiscount% off</span>
                                        </div>
                                    }

                                    <div class="mt-2">

                                        <span class="fw-bold productQuantity me-2">Quantity: @item.Quantity</span>
                                        <a class="fs-6 text-uppercase text-decoration-none " asp-controller="ProductRelated" asp-action="RemoveFromCart" asp-route-cartId="@item.Id">Remove</a>
                                    </div>
                                </div>
                                @*3 in*@
                                <div class="col-3">
                                    @{
                                        var currentDate = DateTime.Now;
                                        //item.Date = item.Date.AddDays();
                                        var difference = currentDate - item.Date;

                                            @*<p>
                                                @difference.Days
                                                @item.Date
                                                @item.Date.DayOfWeek
                                            </p>*@
                                        <p class="text-secondary text-center">
                                            @if (difference.Days > 7)
                                            {
                                                
                                                @item.Date.ToString("dd MMM yyyy")

                                            }
                                            else
                                            {

                                                @item.Date.DayOfWeek
                                            }
                                        </p>
                                    }
                                
                                </div>

                            </div>
                   

                        }
                    </div>

    @*                <div class="card-footer d-flex">
                        <h4 class="me-auto">Cart footer</h4>
                        <button class="btn btn-primary -end">
                            Place Order
                        </button>
                    </div>*@
                </div>
            </div>

    @*        <div class="col-md-4 ">*@
            <div class="col-lg-4 col-md-8 order-1 order-lg-2 mb-3">
                <div class="border rounded">
                    <h4 class="p-2 text-uppercase text-secondary mt-2">Price Details</h4>
                    <hr />
                    <div class="px-5 mb-3 ">
                        <span class="me-auto ">
                            Price Details (@Model.Count)
                        </span> 
                        <span class="float-end  ">
                            ₹ @GrandTotal

                        </span>
                    
                    </div>
                    <div class="px-5 mb-3">
                        <span class="me-auto">
                            Total savings 
                        </span> 
                        <span class="float-end text-success">
                            - ₹ @GrandDiscount

                        </span>
                    
                    </div>
                    <div>

                        <hr style="border: 1px dashed #C0C0C0" class="mx-3"/>
                            <div class="px-5">

                                <span class="fw-bold">Total Amount</span>
                                <span class="fw-bold float-end">@((GrandTotal-GrandDiscount).ToString("c"))</span>
                            </div>
                        <hr style="border: 1px dashed #C0C0C0" class="mx-3"/>
                        @if (GrandTotal > 0)
                        {

                        <div class="row px-4" >
                            <a class="btn btn-danger text-uppercase fw-bold d-block placeOrderButton" asp-controller="ProductRelated" asp-action="PlaceOrder">Place your order</a>
                        </div>
                        }
                    </div>
                </div>
            </div>
        </div>

    </div>
}

Views/ProductRelated/AllOrders.cshtml
@using E_Commerce.Enums; 
@model  IEnumerable<Order>;
<style>
    .fontSize{
        font-size:12px;
        margin-right:12px;
        margin-bottom:5px;
    }
</style>

<script>
    function cancelOrder(productName, orderId) {
        swal("Add To Cart", "Would you like to add " + productName + " into cart???", "info");
        swal({
            title: "Cancel order",
            text: "Would you like to cancel " + productName + " Order ?",
            icon: "info",
            buttons: true
        }).then((result) => {
            if (result) {
                //document.getElementById("AddToCartForm").submit();
            }
        })
    }
</script>
@if (!String.IsNullOrEmpty(TempData["IsOrderCancel"]?.ToString()) ) {
                if (TempData["IsOrderCancel"].ToString()=="True")
                {

                    <h1>order cancel</h1>
                }
                else
                {
                    <h1>Something went wrong</h1>
                }
}



    <div class="container">

        <h4>All orders</h4>
        <hr />



        <div>
            @foreach (var product in Model)
            {
                <div class="card mb-2 shadow-sm p-3 row flex-row">
                    <div class="cartListImageDiv border p-2 col-2">
                        <img class="img-fluid cartImage" src="@product.ProductCoverImage" alt="Alternate Text" />
                    </div>

                    <div class="col-6">

                        <span class="fs-5">@product.ProductName</span> <br />
                        <span class="text-primary  badge bg-primary text-white ">Saler : @product.ProductSalerName</span> <br />

                        <span class="fw-bold">Quantity : @product.ProductQuantity</span>
                    </div>
                    
                    <div class="col-2">
                        <span class="text-muted">₹ @product.ProcuctPrice </span>

                    </div>
                    
                    <div class="col-md-2 col-6 offset-2 offset-md-0 mt-2 mt-md-0">
                        
                        @if (@product.OrderStatus == (int)OrderStatus.Ordered)
                        {
                            <span class="text-success fontSize">
                                <i class="fa-solid fa-circle"></i>
                                <span class="fw-bold text-black">

                                    Ordered
                                </span>
                            </span>
                        }
                        else if (product.OrderStatus == (int)OrderStatus.Shipped)
                        {
                            <span class="text-success fontSize">
                                <i class="fa-solid fa-circle"></i>
                                <span class="fw-bold text-black">
                                    Shipped
                                </span>
                            </span>
                        }
                        else if (product.OrderStatus == (int)OrderStatus.OutForDelevery)
                        {
                            <span class="text-success fontSize">
                                <i class="fa-solid fa-circle"></i>
                                <span class="fw-bold text-black">
                                    Out for Delevery
                                </span>
                            </span>
                        }
                        else if (product.OrderStatus == (int)OrderStatus.Delevered)
                        {
                            <span class="text-success fontSize" style="background-color:lightseagreen; padding:5px; font-size:10px; border:1px solid green; border-radius:15px;">
                                <i class="fa-solid fa-circle"></i>
                                <span class="fw-bold text-white">
                                    Delivered
                                </span>
                            </span>
                        }
                        else if (product.OrderStatus == (int)OrderStatus.Cancel)
                        {
                            <span class="text-danger fontSize">
                                <i class="fa-solid fa-circle"></i>
                                <span class="fw-bold text-black">
                                    Cancelled
                                </span>
                            </span>
                        }
                        @if(product.OrderStatus>=(int) OrderStatus.Ordered && product.OrderStatus < (int)OrderStatus.Shipped)
                        {
                            <button class="btn btn-danger ml-2  btn-sm" onclick="cancelOrder('@product.ProductName',@product.Id)">Cancel order</button>
                            @*<a class="btn btn-danger ml-2  btn-sm" asp-controller="ProductRelated" asp-action="CancelOrder" asp-route-id="@product.Id" >Cancel order</a>*@

                        }
                    </div>
                </div>


            }
        </div>
    </div>

Views/ProductRelated/GetProduct.cshtml
@model E_Commerce.Areas.Admin.Models.ProductModel;






@{
    ViewData["title"] = "get Book";
}

@{ 
    Model.Quantity = 1;
}
<script>

    function incrementQuantity(count) {
        var quantity = document.getElementById('Quantity');
        if (quantity.value > 4 || quantity.value >= count) {
            swal("Quantity", "You can add maximum 5 or available Quantity in cart..!", "info");
        } else {
            quantity.value = parseInt(quantity.value) + 1;
        }

    }

    function decrementQuantity() {

        var quantity = document.getElementById('Quantity');
        if (quantity.value != 1) {

            quantity.value = parseInt(quantity.value) - 1;
        } else {

            swal("Quantity", "You should have at least one product quantity..!", "info");
        }



    }
    console.log("Hello");
    function AddToCartEvent(productName) {
        //console.log("Addtoevent");
        //alert("message");
        swal("Add To Cart", "Would you like to add "+productName+" into cart???", "info");
        swal({
            title: "Add To Cart",
            text: "Would you like to add " + productName + " into cart ?",
            icon: "info",
            buttons: true
        }).then((result) => {
            if (result) {
                document.getElementById("AddToCartForm").submit();
            }
        })

    }


    function AddToCartForOrderEvent(productId) {
        alert('Order button clicked ' + productId);
        var obj = document.getElementById('orderStatus');
        obj.value = 'order';
        document.getElementById('AddToCartForm').submit();
    }


</script>

    @if(TempData["IsAddedIntoCart"]?.ToString() == "True") {
        <script>
            swal('Added into cart', 'Product added into cart..!', 'success');
        </script>
    }

<div class="container">
    @if (Model.IsInOrder) { 
        <div class="alert alert-warning d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Info:"><use xlink:href="#exclamation-triangle-fill" /></svg>

            <span>This product's order currently in panding click <strong> Complete order </strong> to proceed.</span>
            <div class="me-auto">
            </div>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }

    <h3 class="display-6 my-4">Product details</h3>
    <div class="row">
        <div class="col-md-6 mb-2 ">

            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">

                    @for (int i = 0; i < Model.Gallery.Count(); i++)
                    {
                        <div class='text-center carousel-item @(i==0?"active":"")'>
                            <div style="width:100%; vertical-align:central; height:30rem;" class="text-center d-flex align-items-center justify-content-center">

                                <img class="img-fluid" src="@Model.Gallery[i].Url" />
                            </div>
                        </div>
                    }
                </div>

                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>


        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <h1>@Model.ProductName</h1>
                </div>
            </div>

            <div class="row">
                <span class="col-md-12 text-primary">
                    By : @Model.SalerName
                </span>

            </div>
            @if (Model.Stock == 0)
            {

            <h3 class="badge bg-black">Product out of stock</h3><br />
            }
            <div class="row">
                <p class="fw-bold text-success fs-5">Price ₹ @Convert.ToInt32((Model.Price - ((Model.Price * Model.Discount) / 100)))  <span class="fs-6 mx-2"><strike class="priceStrike">₹ @Model.Price</strike></span>   <span class="text-primary fs-6">@Model.Discount% off</span></p>
            </div>

            <div class="row">
                <div class="col-md-12">
                    @if (Model.Stock > 0 && Model.Stock <= 10)
                    {
                        <p class="fw-bold text-danger">Only @Model.Stock Left     </p>
                    }
                    <p class="description">
                        @Html.Raw(Model.Description)
                    </p>
                </div>
            </div>


            @if (Model.Stock > 0)
            {


                <form id="AddToCartForm" asp-action="AddToCart" asp-controller="ProductRelated">
                    <input asp-for="Id" type="hidden" class="form-control" placeholder="Name here" />


                    <div class="row d-flex flex-row">
                        <div class="mb-2 col-5 col-md-5 col-lg-4">
                            <label class="form-group mb-2 text-black-50 fw-bold">Quantity</label>
                            <div class="input-group mb-3">

                                <button class="btn btn-outline-secondary" onclick="decrementQuantity()" type="button" id="button-addon1">-</button>
                                <input asp-for="Quantity" class="form-control text-center" readonly aria-label="Example text with button addon" aria-describedby="button-addon1">
                                <button class="btn btn-outline-secondary" type="button" onclick="incrementQuantity(@Model.Stock)" id="button-addon1">+</button>
                            </div>

                        </div>



                        <input type="hidden" name="productStatus" id="orderStatus" value="" />
                        <div class="col-md-12">

                            @if (Model.IsInCart)
                            {
                                <a data-toggle="modal" class="btn btn-outline-primary me-2" asp-controller="ProductRelated" asp-action="AllCartProducts" data-target="#exampleModal">
                                    <i class="fa-solid fa-cart-shopping"></i> Go to cart
                                </a>

                            }
                            else
                            {
                                <a id="AddToCartData" onClick="AddToCartEvent('@Model.ProductName');" class="btn btn-outline-primary me-2">
                                    <i class="fa-solid fa-cart-plus me-2"></i> Add to cart
                                </a>

                            }

                            @if (!Model.IsInOrder)
                            {

                                <a data-toggle="modal" onClick="AddToCartForOrderEvent(@Model.Id);" class="btn btn-outline-primary" data-target="#exampleModal">
                                    <i class="fa-solid fa-bolt-lightning me-2"></i> Buy Now!
                                </a>

                            }
                            else
                            {
                                
                                <a data-toggle="modal" class="btn btn-outline-primary" asp-controller="productrelated" asp-action="placeorder" asp-route-orderid="@Model.cartId"  data-target="#exampleModal">
                                    <i class="fa-solid fa-bolt-lightning me-2"></i> Complete order
                                </a>
                            }
                        </div>
                    </div>
                </form>
            }
            else
            {

                <a class="btn btn-outline-primary" asp-controller="Home" asp-action="Index">
                    Go back
                </a>
            }

            <hr />
            <ul class="list-group">
                <li class="list-group-item">
                    <span class="fw-bold">
                        Category -
                    </span> @Model.CategoryName
                </li>
                <li class="list-group-item">
                    <span class="fw-bold">
                        @(Model.Stock>0?"Available":"Not available")
                    </span>
                </li>
                <li class="list-group-item">
                    <span class="font-weight-bold">
                        English -
                    </span> @Model.ProductName
                </li>
            </ul>

        </div>
    </div>

    <hr />
    <div class="mt-3">
        <h3>
            Similar books
        </h3>

        <div class="row mt-4 ">


            @for (int i = 0; i < 6; i++)

            {
                <div class="col-md-4 p-2">
                    <div class="card">

                        <img width="100" src="https://media.istockphoto.com/photos/open-sign-at-coffee-cafe-picture-id1156506168?k=20&m=1156506168&s=612x612&w=0&h=WGynjl_RswFKMHGLY-8j1x6J4AtEU5huf2rWPIXJQTU=" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">Title</h5>

                            <p class="card-text">Description</p>

                            <div class="d-flex justify-content-between align-items-center">
                                <a href="#" class="btn btn-primary">View details</a>

                                <small class="text-muted">Author</small>
                            </div>
                        </div>
                    </div>
                </div>



            }
        </div>

    </div>

</div>

Views/ProductRelated/GetProductDetails.cshtml
@model E_Commerce.Areas.Admin.Models.ProductModel;






<h1>@Model.ProductName</h1>



<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        @for (int i = 0; i < Model.Gallery.Count(); i++)
        {
            <div class='carousel-item @(i==0?"active":"")'>

                <img src="@Model.Gallery[i].Url" />
            </div>
        }
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>